### ISSUE TITLE
Look into Samotop and it's efforts / smtp grammars etc

### ISSUE THREAD

**Issue by hpk42** [async-email/async-smtp#2]
https://gitlab.com/BrightOpen/BackYard/Samotop/ 

> SMTP Relay Server (MTA) library and a sample simple server implemented in Rust with focus on spam elimination and privacy. The motivation is to revive e-mail infrastructure and architecture, address current problems and allow new systems to integrate SMTP. It's called SaMoToP, which could be a nice Czech word.

**Comment by jocutajar** [comment]
Anything you need to know?

**Comment by hpk42** [comment]
Hey, thanks for appearing and asking :) 
There is no immediate question but maybe it's interesting for you to hear that @dignifiedquire and me have had several discussions towards a new SMTP/IMAP async-rust server that is able vast amounts of active connections, and for a MVP implements enough so that it can work well with https://delta.chat whose core is implemented fully in Rust (used by all apps on all platforms) and in turn using async-email repos itself ...  maybe we could do an a/v about this sometime?

**Comment by jocutajar** [comment]
Ehlo, yes, I'm very interested. What is _vast_ in your terms? Why not postfix or another big boy? I supect latency is a big deal for delta.chat. We can meet.jit.si ;)

**Comment by hpk42** [comment]
message you from holger at deltachat de -- as to "vast" it's a not quantified ... we were trying to find out the kernel-limits, but 100K active smtp/dovecot connections seems to be doable, with in-ram delivery so that when in many cases, when smtp-send-mail says "250 ok" the message is already imap-delivered to the recipient(s) and has never been written to disc.  Another goal is to get a cargo-installed server, easy to configure and deploy a best-practise smtp server. Postfix/Dovecot are a fine combination today but that doesn't need to stop playing with some potential game-changing innovations :)

**Comment by hpk42** [comment]
If you are interested, @jocutajar, let us still talk some time again, you can contact me at holger at deltachat de anytime ;)
