### ISSUE TITLE
Can this library run in WASM?

### ISSUE THREAD

**Issue by amaury1093** [async-email/async-smtp#23]
I'm looking to deploy my code to Cloudfare workers, and it uses this library. I was wondering, do you plan to support WASM as build target?

I just tried now, and had a small error, due to the `hostname` dependency (maybe others?).

```
error: Unsupported target OS! Create an issue: https://github.com/svartalf/hostname/issues/new
  --> /Users/amaurymartiny/.cargo/registry/src/github.com-1ecc6299db9ec823/hostname-0.3.1/src/lib.rs:81:9
   |
81 |         compile_error!("Unsupported target OS! Create an issue: https://github.com/svartalf/hostname/issues/new");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared type or module `sys`
   --> /Users/amaurymartiny/.cargo/registry/src/github.com-1ecc6299db9ec823/hostname-0.3.1/src/lib.rs:105:5
    |
105 |     sys::get()
    |     ^^^ use of undeclared type or module `sys`

error: aborting due to 2 previous errors
```

We could return `localhost` in wasm.

**Comment by link2xt** [comment]
I opened a PR https://github.com/async-email/async-smtp/pull/66 to remove `hostname` dependency. There is still a problem with some `tokio` features in dev-dependencies, but otherwise it should compile to `wasm32-wasip2`.

**Comment by link2xt** [comment]
CI now checks `wasm32-wasip2` target.
