### ISSUE TITLE
Machine hostname is exposed to the server

### ISSUE THREAD

**Issue by link2xt** [async-email/async-smtp#25]
HELO command sends `ClientId::hostname()` result which exposes machine hostname to the server.

Some server add it to `Received` header: https://support.delta.chat/t/delta-chat-disroot-expose-ip-and-machine-name-on-headers/1081

A way to override it is needed, and maybe a better default, such as `localhost` always.

**Comment by gerryfrancis** [comment]
> maybe a better default, such as localhost always

@link2xt `localhost` is reserved to IP address 127.0.0.1. Shall the real address be exchanged with the one of `localhost`?
