### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by link2xt** [async-email/async-smtp#59]
Mostly because of #57 and https://github.com/deltachat/deltachat-core-rust/pull/3985

**Comment by dignifiedquire** [comment]
Do you mean `3.0.0`?

**Comment by dignifiedquire** [comment]
Wait, I am very confused

- https://github.com/async-email/async-smtp/blob/master/Cargo.toml#L4 shows `2.0.0`
- https://crates.io/crates/async-smtp shows `0.6.0`

**Comment by dignifiedquire** [comment]
Done

**Comment by link2xt** [comment]
Now we have version 0.6 followed by 0.8 :)
It's ok, thanks!

**Comment by dignifiedquire** [comment]
yeah.. cargo-release automatically bumps the version when I run it 😅
