### ISSUE TITLE
Adding example with starttls

### ISSUE THREAD

**Issue by MattBlack85** [async-email/async-smtp#60]
Hi!, Is it possible to add an example with how to use Credentials and starttls? I can't figure it out and my calls are never returning at the moment

**Comment by link2xt** [comment]
You can look at how Delta Chat uses it at https://github.com/deltachat/deltachat-core-rust/blob/fc019de18ccfd52a9373ac284170238e440e7cb2/src/smtp.rs#L190-L211

**Comment by MattBlack85** [comment]
thanks @link2xt that is exactly what I needed!
